#/usr/bin/python

class MicroServiceName:
    MONTH_CARD = "card"
    CITY_CODE = "citycode"
    GAEA = "gaea"
    SECURITY = "security-service"
    SMS = "sms"
    BIKE_SERVICE = "bike-service"
    USER_API = "user-api"
    USER_INFO = "user-info"
    USER_MEMBER = "user-member"
    WECHAT = 'wechat'
    APPCONFIG_GAMMA = 'appconfig-gamma'
    TRIP_RIDINGTRACK = "trip-ridingtrack"
    PAY_MENT = "payment"
    TRIP_ORDER = "trip-order"
    TRIALPERIOD = "trialperiod"
    ORTHRUS_BASICINFO = "orthrus-basicinfo"
    ORTHRUS_PLATFORM = "orthrus-platform"
    ORTHRUS_ORDER = "orthrus-order"
    MOCAR_API = "mocar-api"
    MOCAR_INTERNAL_API = "mocar-internal-api"
    PARTNER = "partner"
    PANDORA_COUPON = "pandora-coupon"
    MODOUV2 = "mobean"
    MUSHTANG = "mustang"
    GANDALF_SERVER = "gandalf-server"
    HTTPDNS = "infra-httpdns"
    USER_ROAMING = "user-roaming"
    USER_AUTH = "user-auth"
    USER_REGION = "user-region"
    USER_MIX = "user-mix"
    PAY_CORE = "pay-core"